apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  template:
    metadata:
      labels:
        app: authservice
    spec:
      # This section describes the containers that make up the deployment
      containers:
        - name: authservice
          image: gcr.io/stone-timing-278916/authservice
          ports:
            - containerPort: 8080
          # Set env variables used for Postgres Connection
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pgsql-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pgsql-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cloudsql-pgsql-credentials
                  key: dbname
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is $PROJECT:$REGION:$INSTANCE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=stone-timing-278916:us-central1-f:memegen-db=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: my-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authservice
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: default
  labels:
    app: authservice
spec:
  selector:
    app: authservice
  ports:
  - name: http
    port: 8080
    protocol: TCP
  type: #SVC_TYPE#

